version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./megano/Dockerfile.prod
    command: gunicorn megano.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - static_volume:/home/megano_app/web/megano/staticfiles
      - media_volume:/home/megano_app/web/megano/uploads

    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/megano_app/web/megano/staticfiles
      - media_volume:/home/megano_app/web/megano/uploads
    ports:
      - 1337:80
    depends_on:
      - web


  redis:
    image: redis:7.0.5-alpine
    hostname: worker
  worker:
    build:
      context: .
      dockerfile: ./megano/Dockerfile.prod
    hostname: worker
    entrypoint: celery
    command: -A celery_app worker --loglevel=info -P eventlet
    volumes:
      - static_volume:/home/megano_app/web/megano/staticfiles
      - media_volume:/home/megano_app/web/megano/uploads
    links:
      - redis
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
  beat:
    build:
      context: .
      dockerfile: ./megano/Dockerfile.prod
    entrypoint: celery
    command: -A celery_app beat --loglevel=info
    volumes:
      - static_volume:/home/megano_app/web/megano/staticfiles
      - media_volume:/home/megano_app/web/megano/uploads
    links:
      - redis
      - worker
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod

  flower:
    build:
      context: .
      dockerfile: ./megano/Dockerfile.prod
    hostname: flower
    entrypoint: celery
    command: -A celery_app flower
    volumes:
      - static_volume:/home/megano_app/web/megano/staticfiles
      - media_volume:/home/megano_app/web/megano/uploads
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"





volumes:
  postgres_data:
  static_volume:
  media_volume:


