version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./megano/Dockerfile.prod
    command: gunicorn megano.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - static_volume:/home/megano_app/web/megano/staticfiles
      - media_volume:/home/megano_app/web/megano/uploads

    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/megano_app/web/megano/staticfiles
      - media_volume:/home/megano_app/web/megano/uploads
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:


