version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./megano/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
#    command: /usr/src/megano/entrypoint.sh
    volumes:
      - ./megano/:/usr/src/diploma/megano
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=megano_app
      - POSTGRES_PASSWORD=megano_app
      - POSTGRES_DB=megano_app_dev

volumes:
  postgres_data:
