# Generated by Django 4.2.6 on 2023-11-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_remove_profile_avatar_profile_email_profile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='src',
        ),
        migrations.AddField(
            model_name='avatar',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
