# Generated by Django 4.2.6 on 2023-12-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0007_saledate'),
        ('myorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('count', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='myorders.order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='mycatalog.product')),
            ],
        ),
    ]
