# Generated by Django 4.2.6 on 2023-12-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myorders', '0003_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('code', models.IntegerField()),
                ('order_rel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myorders.order')),
            ],
        ),
    ]
