# Generated by Django 4.2.6 on 2024-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
