# Generated by Django 4.2.6 on 2023-11-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0002_remove_product_images_alter_product_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='mycatalog.product'),
        ),
    ]
