# Generated by Django 4.2.6 on 2023-12-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycatalog', '0006_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('discount', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='mycatalog.product')),
            ],
        ),
    ]
